### ISSUE TITLE
Loss of feature

### ISSUE THREAD

**Issue by JohnsenZhou** [Twipped/Kalendae#221]
Hi,thank you for your awesome opensource Kalendae. I found a feature lost in the file which named: kalendae.standalone.min. The feature is 'removeAllSelected()'.

**Comment by Twipped** [comment]
Nope, it's still there.
![image](https://user-images.githubusercontent.com/231157/35343409-7057ccf6-00df-11e8-90e4-5486c61a7f3b.png)

**Comment by JohnsenZhou** [comment]
Sorry, maybe the feature lost when i copy the file.
thank u for your answer  👍
