### ISSUE TITLE
IE10, eval(), defer and async issue.

### ISSUE THREAD

**Issue by Krutoy-4el** [Twipped/Kalendae#232]
Your library is really very good, but it wasn't working on:
 - IE10,
 - with JavaScript eval() function and defer/async attributes on Chrome,
 - with eval() and defer on Firefox (my Firefox is outdated, so it may be fixed in newer versions of it).

The error was "Kalendae.Input is not a constructor".
I thought it was because of definition order. I made this fix to the Makefile and now it runs everywhere:
`kal=src/intro_standalone.js \
	src/MinPubSub.js \
	src/moment.js \
	src/main.js \
	src/moment.ext.js \
	src/util.js \
	src/input.js \
	src/auto.js \
	src/jq.js \
	src/outro.js`
I've only changed the order of files, so I think I didn't break anything.
I haven't fix kmomentless because of my lazyness :)
I hope you'll perform my fix to your Makefile and will fix the momentless build.
If not, please write shortly why it mustn't be done.
I'm enclosing my Makefile to this issue.
[Makefile.zip](https://github.com/Twipped/Kalendae/files/4421213/Makefile.zip)

Hope to your response, thanks for developing!

**Comment by Twipped** [comment]
Fixed in c8768ce (1.0.2). How strange that in 8 years since IE10 was released, nobody ever encountered this.
